Optimize manifest creation process

diff --git a/.github/workflows/build-and-push.yaml b/.github/workflows/build-and-push.yaml
--- a/.github/workflows/build-and-push.yaml
+++ b/.github/workflows/build-and-push.yaml
@@ -155,21 +155,16 @@ jobs:
         env:
           REGISTRY_PACKAGE: ${{ env.REGISTRY_PACKAGE }}
         run: |
-          set +e
-          OUTPUT=$(docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
-            $(printf "${REGISTRY_PACKAGE}@sha256:%s " *) 2>&1)
+          echo "Creating manifest"
+          if ! OUTPUT=$(docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
+                          $(printf "${REGISTRY_PACKAGE}@sha256:%s " *) 2>&1)
+            echo "Manifest creation failed"
+            echo "${OUTPUT}"
+            exit 1
+          fi
 
-          STATUS=$?
-
-            if [ $STATUS -ne 0 ]; then
-              echo "Manifest creation failed"
-              echo "$OUTPUT"
-            exit $STATUS
-            fi
-
-            echo "Manifest created"
-            echo "$OUTPUT"
-          set -e
+          echo "Manifest created successfully"
+          echo "${OUTPUT}"
 
           # Extract digest SHA for subsequent steps
           GET_DIGEST_SHA="$(echo "$OUTPUT" | grep -oE 'sha256:[a-f0-9]{64}' | tail -1)"
